config/routes.rb
Rails.application.routes.draw do
  get 'sales/done'
  resources :sales
  # get 'sales/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :cod, uniqueness: true
  validates :detail, presence: true
  validates :category, inclusion: { in: %w(uno dos tres cuatro cinco),
    message: "%{value} no es una categoría permitida" }
  validates :value, numericality: { only_integer: true, greater_than: 0 }
  validates :discount, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
      if @sale.tax == 1
        taxes = @sale.value - (@sale.value * 19/100)
        Sale.new(sale_params)
      else
        @sale.value - @sale.discount
      end


    if @sale.save
      redirect_to sales_done_path
    else
      render :new
    end
  end

  def done
    @sale = Sale.last
  end

  private
  def sale_params
    params.require(:sale).permit(:cod, :detail, :category, :value, :discount, :tax, :total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VntasDyneng</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/done.html.erb
<h2>El registro fue almacenado con éxito!</h2>

<p> <%=@sale.cod%> </p>
<p> <%=@sale.detail%> </p>
<p> <%=@sale.category%> </p>
<p> <%=@sale.value%> </p>
<p> <%=@sale.discount%> </p>
<p> <%=@sale.tax%> </p>
<p> <%=@sale.total%> </p>

<%= link_to 'Volver', new_sale_path %>

app/views/sales/new.html.erb
<h2>Nuevas Ventas</h2>

<%= form_with model: @sale do |f| %>
  <%= f.label :codigo_venta %>:
  <%= f.number_field :cod %><br />

  <%= f.label :detalle %>:
  <%= f.text_area :detail %><br />

  <%= f.label :categoria %>:
  <%= f.text_field :category %><br />

  <%= f.label :precio %>:
  <%= f.number_field :value %><br />

  <%= f.label :descuento %>:
  <%= f.number_field :discount %><br />

  <%= f.label :exento_de_iva %>:
  <%= f.check_box :tax %><br />

  <%= f.submit "Enviar" %>
<% end %>

<%= @sale.errors %>